"""agrego entidades deposito y deposito_proveedor

Revision ID: b9814b40a536
Revises: c9d6e0ce7479
Create Date: 2024-10-13 19:43:17.134004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9814b40a536'
down_revision = 'c9d6e0ce7479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depositos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposito_proveedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deposito_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deposito_id'], ['depositos.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposito_proveedor')
    op.drop_table('depositos')
    # ### end Alembic commands ###
