"""agrego atributo material a la tabla orden

Revision ID: c9d6e0ce7479
Revises: 
Create Date: 2024-10-13 17:29:25.126642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d6e0ce7479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('material', sa.Integer(), nullable=False))  # Comentar o eliminar esta línea
        batch_op.create_foreign_key(None, 'materiales', ['material'], ['id'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('material')

    # ### end Alembic commands ###
