"""Agregar columna material_id a deposito_proveedor

Revision ID: d7690f4d3a98
Revises: 4499d4bc7a86
Create Date: 2024-11-30 06:42:55.583161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7690f4d3a98'
down_revision = '4499d4bc7a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposito_proveedor', sa.Column('material_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deposito_proveedor', 'materiales', ['material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deposito_proveedor', type_='foreignkey')
    op.drop_column('deposito_proveedor', 'material_id')
    # ### end Alembic commands ###
