"""creacion tabla ordendistribucion

Revision ID: eae21f7bda57
Revises: 541dafc1b45d
Create Date: 2024-11-30 09:19:08.041650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae21f7bda57'
down_revision = '541dafc1b45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_distribucion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('necesidad_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['necesidad_id'], ['necesidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenes_distribucion')
    # ### end Alembic commands ###
