# Usa una imagen oficial de Python 3.10
FROM python:3.10-slim

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el archivo de requerimientos al contenedor
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación al contenedor
COPY . .

# Establecer las variables de entorno necesarias
ENV FLASK_APP=run.py
ENV FLASK_ENV=production  

# Exponer el puerto que usará la aplicación
EXPOSE 8000

# Comando para ejecutar Gunicorn con la aplicación
CMD ["gunicorn", "-b", "0.0.0.0:8000", "--access-logfile", "-", "run:app"]
