services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/api_database
      - JWT_SECRET_KEY=dssd-grupo3
    depends_on:
      - db
    volumes:
      - .:/app  # Esto monta el directorio actual en el contenedor

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  # Ruta a tu init.sql en db-scripts
    ports:
      - "5433:5432"

volumes:
  postgres_data:
