version: '3'
services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al puerto 8000 de la máquina local
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/api_database
      - JWT_SECRET_KEY=dssd-grupo3
    depends_on:
      - db  # Asegura que la base de datos se levante antes de la API
    volumes:
      - .:/app  # Monta el directorio actual en el contenedor, útil para desarrollo

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Mapea el puerto 5433 del host al puerto 5432 del contenedor (PostgreSQL)

volumes:
  postgres_data:
